config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'posts/:id/confirm' => 'posts#confirm', as: 'confirm'
  get 'posts/:id/confirm2' => 'posts#confirm2', as: 'confirm2'

  root "posts#index"
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/posts/:id/likes' => 'posts#likes', as: 'like'
  get 'search' => "posts#search", as: 'search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :file, ImageUploader
 
    # 이미지를 가진 게시글 삭제 시 AWS S3서버에도 자동 삭제처리
    before_destroy :destroy_assets
 
    def destroy_assets
        self.file.remove! if self.file
        self.save!
    end
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :impressions, :as=>:impressionable
 
   def impression_count
       impressions.size
   end
 
   def unique_impression_count
       # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
       # so getting keys from the hash and calculating the number of keys
       impressions.group(:ip_address).size.keys.length #TESTED
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
 
    def new
      @image = Image.build.params(image_params)
    end
   
    def show
      @image = Image.find(params[:id])
    end
   
    private
   
    def image_params
      params.require(:image).permit(:file, :hint, :alt, :post_id, :all_notice_id)
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :confirm, :confirm2, :likes]

  before_action :log_impression, :only=> [:show]
 
   def log_impression
      @hit_post = Post.find(params[:id])
      # this assumes you have a current_user method in your authentication system
      @hit_post.impressions.create(ip_address: request.remote_ip)
   end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("updated_at DESC")
    if Post.all.count >= 3
      @viewposts = Post.order("likes DESC")[0..2]
      @likeposts = Post.order("views DESC")[0..2]
    else
      @viewposts = Post.none
      @likeposts = Post.none
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    newviews = @post.views + 1
    @post.update(views: newviews)
  end

  def confirm
    
  end
  def confirm2
    
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.password != params[:password]
      redirect_to posts_path
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.password != params[:password]
      puts @post.password
      puts params[:password]
      redirect_to posts_path
    end

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def likes
    num_like = @post.likes + 1
    if @post.update(likes: num_like)
      redirect_back fallback_location: { action: "show", id: @post.id }
    end
  end

  def search
    p_search = params[:search]
    p_all = Post.order("updated_at DESC")
    p_id = []
    case p_search[:select]
    when "title"
      p_all.each do |p|
        if p.title.include? p_search[:query]
          p_id.push(p.id)
        end
      end
      @posts = Post.where(id: p_id).order("updated_at DESC")
    when "content"
      p_all.each do |p|
        if p.content.include? p_search[:query]
          p_id.push(p.id)
        end
      end
      @posts = Post.where(id: p_id).order("updated_at DESC")
    else
      @posts = Post.none
    end
    if Post.all.count >= 3
      @viewposts = Post.order("likes DESC")[0..3]
      @likeposts = Post.order("views DESC")[0..3]
    else
      @viewposts = Post.none
      @likeposts = Post.none
    end
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :row, :column, :status, :summary, :password)
    end
end

app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController
    def create
      # Take upload from params[:file] and store it somehow...
      # Optionally also accept params[:hint] and consume if needed
      image = Image.create(:file => params[:file])
      params.permit(:file, :alt, :hint)
   
      render json: {
        image: {
          url: image.file.url
        }
      }, content_type: "text/html"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delaython</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="js/script.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Gothic+A1:400,500,600,700" rel="stylesheet">

  </head>

  <body class="container">
  <div class="d-flex flex-row justify-content-center">
    <div>
      <%= image_tag("babylogo.png", class:"logo")%>
    </div>
    <div>
      <a href="https://uni.likelion.org/hackathon/projects/93" target="_blank">
        <%= image_tag("selload_logo.png", class: "logo2")%>
      </a>
    </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group row">
    <%= form.label :"서비스 이름", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class:"form-control" %>
    </div>
  </div>

  <div class="field form-group row">
    <%= form.label :"서비스 간단요약", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :summary, class:"form-control" %>
    </div>
  </div> 

  <div class="field">
    <%= tinymce :language => "en" %>
    <%= form.text_area :content, id: :post_content, class: "form-control tinymce", rows: "10" %>
</div>

  <div class="field form-group row" style="margin-top: 20px">
    <div class="col-sm-2 col-form-label">개발상태</div>
    <div class-"col-sm-10">
      <%= form.radio_button :status,'1', :checked => true %> 
      <%= label :status_1, '코딩다함 보러오셈 히히', style:"margin-right: 40px" %>
      <%= form.radio_button :status, '2' %>
      <%= label :status_2, '아직 코딩중.. ㅠ', style:"margin-right: 40px" %>
      <%= form.radio_button :status, '3' %>
      <%= label :status_3, '걍 포기함 다 망함' %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-2 col-sm-4">팀 테이블 위치</div>
    <div class="field col-lg-2 col-sm-4">
      <%= form.label :"왼쪽부터" %>
      <%= form.select :column,  options_for_select([[1,0],[2,1],[3,2],[4,3],[5,4],[6,5],[7,6]], :column) %>
      번째
    </div>

    <div class="field col-lg-2 col-sm-4">
      <%= form.label :"앞에서부터" %>
      <%= form.select :row, options_for_select((1..5).step(1), :row) %>
      번째
    </div>
    <div class="col-lg-1"></div>
    <div class="field form-group col-lg-5 row">
      <%= form.label :password, class:"col-lg-2 col-sm-2 col-form-label" %>
      <div class="col-lg-10 col-sm-10">
      <%= form.password_field :password, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-lg btn-primary float-right", style:"margin-top: 20px" %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<form action="/posts/<%=@post.id%>/edit", method="get">
  비밀번호: <input type="password" name="password"><br>
  <input type="submit" value="Submit">
</form>

app/views/posts/confirm2.html.erb
<form action="/posts/<%=@post.id%>", method="delete">
  비밀번호: <input type="password" name="password"><br>
  <input type="submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex flex-row justify-content-around">
  <div>
    <p class="font5">실시간 조회수 TOP</P>
    <% @viewposts.each do |viewpost| %>
      <p class="font4" style="text-align: center"><%= link_to viewpost.title, viewpost %></p>
    <% end %>
  </div>
  <div>
    <p class="font5">실시간 추천수 TOP</P>
    <% @likeposts.each do |likepost| %>
      <p class="font4" style="text-align: center"><%= link_to likepost.title, likepost %></p>
    <% end %>
  </div>
</div>


<table class="table table-borderless container">
  <thead>
    <tr>
      <th>팀</th>
      <th>likes</th>
      <th>views</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class="font2"><%= link_to post.title, post, :class => "font1" %> <br> <%= post.summary %> </td>
        <td colspan="1" width="5%" align="left" style="border-bottom: 1px dashed gray;" class="font3"><%= post.likes  %></td>
        <td colspan="1" width="5%" align="left" style="border-bottom: 1px dashed gray;" class="font3"> <%= "#{post.unique_impression_count}" %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="searchbar">
  <%= form_tag search_path, method: :get do %>
    <%= select_tag("search[select]", options_for_select([["제목","title"],["내용","content"]] )) %>
    <%= text_field_tag "search[query]" %>
    <%= submit_tag("Search") %>
  <% end %>
</div>

<div class="searchbar2">
  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1 style="margin-bottom: 50px; margin-top: 40px">등록하기</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-title">
  <%= @post.title %>
</div>
<div class="d-flex justify-content-between">
  <div class="show-sub">
    <%= @post.summary %>
  </div>

  <div>
    <div class="btn btn-lg btn-success">
      <% if @post.status == "1" %>
        <strong>개발완료</strong>
      <% elsif @post.status == "2"%>
        <strong>개발중</strong>
      <% else %>
        <strong>포기</strong>
      <% end%>
    </div>

    <div class="float-right" style="display: inline; text-align:center; margin-left: 20px">
      <%= link_to '', like_path(@post), class:'fas fa-thumbs-up ha', style:'font-size: 2.4em' %>
      <h1 style="display:inline"><strong><%= @post.likes %></strong></h1>
    </div>
  </div>
</div>

<div class="show-content">
  <%= @post.content.html_safe %>
</div>

<h1>방문해서 더 자세히 보려면! <strong>팀테이블 위치<strong></h1>
<br>
<div class="float-center">
  <div class="stage">무대</div>
  <div class="divTable">
    <div class="divTableBody">
      <div class="divTableRow 1">
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
      </div>
      <div class="divTableRow 2">
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
      </div>
      <div class="divTableRow 3">
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
      </div>
      <div class="divTableRow 4">
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
      </div>
      <div class="divTableRow 5">
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
        <div class="divTableCell">&nbsp;</div>
      </div>
    </div>
  </div>
</div>

<div class="text-right" style="margin-top:40px">
<%= link_to '수정하기', confirm_path(@post), class:'btn btn-lg btn-light'%>
<%= link_to '뒤로가기', posts_path, class:"btn btn-lg btn-light" %>
</div>

<script>
var row=<%=@post.row%>
var col=<%=@post.column%>
console.log(row)
console.log(col)
$(`.divTableRow.${row}`).children().eq(col).addClass("selected")
</script>